import setA1 from "./Images/card_1_1.png"
import setA2 from "./Images/card_1_2.png"
import setA3 from "./Images/card_1_3.png"
import setA4 from "./Images/card_1_4.png"
import setA5 from "./Images/card_1_5.png"
import setA6 from "./Images/card_1_6.png"
import setA7 from "./Images/card_1_7.png"
import setA8 from "./Images/card_1_8.png"
import setA9 from "./Images/card_1_9.png"
import setA10 from "./Images/card_1_10.png"
import setA11 from "./Images/card_1_11.png"
import setA12 from "./Images/card_1_12.png"
import setA13 from "./Images/card_1_13.png"
import setB1 from "./Images/card_2_1.png"
import setB2 from "./Images/card_2_2.png"
import setB3 from "./Images/card_2_3.png"
import setB4 from "./Images/card_2_4.png"
import setB5 from "./Images/card_2_5.png"
import setB6 from "./Images/card_2_6.png"
import setB7 from "./Images/card_2_7.png"
import setB8 from "./Images/card_2_8.png"
import setB9 from "./Images/card_2_9.png"
import setB10 from "./Images/card_2_10.png"
import setB11 from "./Images/card_2_11.png"
import setB12 from "./Images/card_2_12.png"
import setB13 from "./Images/card_2_13.png"
import setC1 from "./Images/card_3_1.png"
import setC2 from "./Images/card_3_2.png"
import setC3 from "./Images/card_3_3.png"
import setC4 from "./Images/card_3_4.png"
import setC5 from "./Images/card_3_5.png"
import setC6 from "./Images/card_3_6.png"
import setC7 from "./Images/card_3_7.png"
import setC8 from "./Images/card_3_8.png"
import setC9 from "./Images/card_3_9.png"
import setC10 from "./Images/card_3_10.png"
import setC11 from "./Images/card_3_11.png"
import setC12 from "./Images/card_3_12.png"
import setC13 from "./Images/card_3_13.png"
import setD1 from "./Images/card_4_1.png"
import setD2 from "./Images/card_4_2.png"
import setD3 from "./Images/card_4_3.png"
import setD4 from "./Images/card_4_4.png"
import setD5 from "./Images/card_4_5.png"
import setD6 from "./Images/card_4_6.png"
import setD7 from "./Images/card_4_7.png"
import setD8 from "./Images/card_4_8.png"
import setD9 from "./Images/card_4_9.png"
import setD10 from "./Images/card_4_10.png"
import setD11 from "./Images/card_4_11.png"
import setD12 from "./Images/card_4_12.png"
import setD13 from "./Images/card_4_13.png"

export const cardImages = [
    {src: setA1, matched: false},
    {src: setA2, matched: false},
    {src: setA3, matched: false},
    {src: setA4, matched: false},
    {src: setA5, matched: false},
    {src: setA6, matched: false},
    {src: setA7, matched: false},
    {src: setA8, matched: false},
    {src: setA9, matched: false},
    {src: setA10, matched: false},
    {src: setA11, matched: false},
    {src: setA12, matched: false},
    {src: setA13, matched: false},
    {src: setB1, matched: false},
    {src: setB2, matched: false},
    {src: setB3, matched: false},
    {src: setB4, matched: false},
    {src: setB5, matched: false},
    {src: setB6, matched: false},
    {src: setB7, matched: false},
    {src: setB8, matched: false},
    {src: setB9, matched: false},
    {src: setB10, matched: false},
    {src: setB11, matched: false},
    {src: setB12, matched: false},
    {src: setB13, matched: false},
    {src: setC1, matched: false},
    {src: setC2, matched: false},
    {src: setC3, matched: false},
    {src: setC4, matched: false},
    {src: setC5, matched: false},
    {src: setC6, matched: false},
    {src: setC7, matched: false},
    {src: setC8, matched: false},
    {src: setC9, matched: false},
    {src: setC10, matched: false},
    {src: setC11, matched: false},
    {src: setC12, matched: false},
    {src: setC13, matched: false},
    {src: setD1, matched: false},
    {src: setD2, matched: false},
    {src: setD3, matched: false},
    {src: setD4, matched: false},
    {src: setD5, matched: false},
    {src: setD6, matched: false},
    {src: setD7, matched: false},
    {src: setD8, matched: false},
    {src: setD9, matched: false},
    {src: setD10, matched: false},
    {src: setD11, matched: false},
    {src: setD12, matched: false},
    {src: setD13, matched: false},
]